import type {Metadata} from "next";
import "./globals.css";
import Link from 'next/link';
import {ReactNode} from "react";
import ServerBreadcrumbs from "@/components/server-breadcrumbs";

export const metadata: Metadata = {
    title: "My Game of Thrones character app",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <div className="grid grid-cols-12 min-h-screen grid-rows-[auto_1fr]">
            <div id="header" className="col-span-12 border-b-2 border-black">
                <h1 className="text-6xl font-bold text-center m-2">My Game of Thrones character app</h1>
            </div>
            <div id="navbar" className="p-2 border-r-2 border-black col-span-2 flex flex-col gap-2">
                <Link href="/">Home</Link>
                <Link href="/books">Books</Link>
                <Link href="/characters">Characters</Link>
                <Link href="/books">Houses</Link>
            </div>
            <div id="content" className="col-span-10 p-2">
                <ServerBreadcrumbs/>
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
